In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
df= pd.read_csv('movie.csv')

In [3]:
df.shape

(8992, 3)

In [4]:
df.head()

   userId             movie  rating
0       3  Toy Story (1995)     4.0
1       6  Toy Story (1995)     5.0
2       8  Toy Story (1995)     4.0
3      10  Toy Story (1995)     4.0
4      11  Toy Story (1995)     4.5

In [6]:
len(df.userId.unique())

4081

In [8]:
len(df.movie.unique())

10

In [9]:
len(df.rating.unique())

10

In [10]:
df.rating.unique()

array([4. , 5. , 4.5, 3. , 1. , 3.5, 1.5, 2. , 2.5, 0.5])

In [11]:
df.movie.unique()

array(['Toy Story (1995)', 'Jumanji (1995)', 'Grumpier Old Men (1995)',
       'Waiting to Exhale (1995)', 'Father of the Bride Part II (1995)',
       'Heat (1995)', 'Sabrina (1995)', 'Tom and Huck (1995)',
       'Sudden Death (1995)', 'GoldenEye (1995)'], dtype=object)

In [13]:
df.groupby('movie')['rating'].mean().sort_values(ascending=False)

movie
Toy Story (1995)                      3.959323
Heat (1995)                           3.836508
GoldenEye (1995)                      3.427003
Sabrina (1995)                        3.381429
Tom and Huck (1995)                   3.352564
Jumanji (1995)                        3.268398
Grumpier Old Men (1995)               3.186861
Father of the Bride Part II (1995)    3.143836
Sudden Death (1995)                   3.017327
Waiting to Exhale (1995)              3.000000
Name: rating, dtype: float64

##### Cosine Similarity

##### Item-Item

In [16]:
df1=df.pivot_table(index='movie',columns='userId',values='rating')
df1.fillna(0,axis=1,inplace=True)
df1.head()

userId                              1     2     3     ...  7117  7119  7120
movie                                                 ...
Father of the Bride Part II (1995)   0.0   0.0   0.0  ...   0.0   0.0   0.0
GoldenEye (1995)                     0.0   0.0   0.0  ...   3.0   0.0   0.0
Grumpier Old Men (1995)              0.0   4.0   0.0  ...   4.0   0.0   0.0
Heat (1995)                          0.0   0.0   0.0  ...   5.0   0.0   0.0
Jumanji (1995)                       3.5   0.0   0.0  ...   0.0   0.0   4.0

[5 rows x 4081 columns]

In [19]:
similarity= cosine_similarity(df1)

In [21]:
similarity.shape

(10, 10)

In [23]:
similarity[1]

array([0.21599275, 1.        , 0.21819777, 0.39773907, 0.40226034,
       0.22145469, 0.1552551 , 0.11972423, 0.38348625, 0.12844824])

In [28]:
df1.index

Index(['Father of the Bride Part II (1995)', 'GoldenEye (1995)',
       'Grumpier Old Men (1995)', 'Heat (1995)', 'Jumanji (1995)',
       'Sabrina (1995)', 'Sudden Death (1995)', 'Tom and Huck (1995)',
       'Toy Story (1995)', 'Waiting to Exhale (1995)'],
      dtype='object', name='movie')

In [53]:
def recommended_movie(similar_movie):
    if similar_movie in df1.index:
        index= np.where(similar_movie==df1.index)[0][0]
        similar=sorted(list(enumerate(similarity[index])),reverse=True,key=lambda x: x[1])[1:6]

In [41]:
np.where('Sudden Death (1995)'==df1.index)[0][0]

np.int64(6)

In [56]:
index=sorted(list(enumerate(similarity[6])),reverse=True,key=lambda x: x[1])
index

[(6, np.float64(1.0)),
 (3, np.float64(0.25562861545717425)),
 (2, np.float64(0.25538652387425004)),
 (0, np.float64(0.22645758856153095)),
 (5, np.float64(0.20155613932348176)),
 (8, np.float64(0.16679264647501568)),
 (1, np.float64(0.15525510280522925)),
 (9, np.float64(0.1517997172732899)),
 (4, np.float64(0.14328579279207665)),
 (7, np.float64(0.0972133840188559))]

In [43]:
list1=[1,2,3]

In [45]:
for i in enumerate(list1):
    print(i)

(0, 1)
(1, 2)
(2, 3)